In [2]:
import numpy as np
import pandas as pd

In [3]:
from pandas import Series,DataFrame 
# 由于series和dataframe用的较多，此代码用于将其引入本地命名空间

In [4]:
import numpy as np
np.random.seed(12345) #生成随机数种子，使结果一致
import matplotlib.pyplot as plt #导入matplotlib的画笔工具pyplot，简称为plt
plt.rc("figure",figsize=(10,6)) #rc指run command（运行配置），将该文件的全部绘图长宽默认为10*6
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
# 把系统原本默认的“最大显示行数”存到一个变量里当作备份
pd.options.display.max_rows = 20
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 80
# 设置屏幕最多显示20行，20列，每格单元格最多显示80个字符
np.set_printoptions(precision=4,suppress=True)
#设定numpy矩阵打印规则，precision=4表明只保留小数点后四位，suppress=true表明不使用科学计数法

In [5]:
obj = pd.Series([4,7,-5,3])
print(obj)
# 将填入的列表绑定序号（series），左边为行号index，下面为该列的数据类型

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.array
print(obj.array) #提取出数据和类型等
print(obj.values) #只提取数据

obj.index #只提取索引

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64
[ 4  7 -5  3]

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3],
                 index=["d","b","a","c"])
# ["a","b"...]不设置单引号或双引号则视为变量
print(obj2)
obj2.index #jupyter特有的最后一行代码块会展示，写在中间将不会打印结果，在.py的文件中也不会显示

d    4
b    7
a   -5
c    3
dtype: int64

Index(['d', 'b', 'a', 'c'], dtype='str')

In [8]:
obj2["a"]
obj2["d"]=6
obj2[["c","a","d"]]

c    3
a   -5
d    6
dtype: int64

obj2["d"] = 6 用于修改数值
obj2[["c","a","d"]] 为批量抽取，注意有两层[[]],第一层为对应obj2，第二次为列表，从中取值

In [9]:
print(obj2[obj2 > 0])
print(obj2 * 2)
print(np.exp(obj2))

d    6
b    7
c    3
dtype: int64
d    12
b    14
a   -10
c     6
dtype: int64
d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [10]:
"b" in obj2
"e" in obj2

False

In [11]:
sdata = {"Ohio": 35000,"Texas": 71000,"Oregon": 16000,"Utah": 5000}
obj3 = pd.Series(sdata)
obj3
# 数据存放在字典中，可直接通过字典创建series

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [12]:
states = ["California","Ohio","Oregon","Texas"]
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

键key 绝对唯一，不可变（字符串，数字或元组；不能拿list当键）
值value 无限制，可重复

In [13]:
pd.isnull(obj4)
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [14]:
obj4.isna()
# pandas.isnull或series的isna 用于检测缺失数据

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [15]:
print(obj3)
print(obj4)
obj3 + obj4
# Series会根据索引标签自动对齐数据

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [16]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [17]:
obj
obj.index = ["Bob","Steve","Jeff","Ryan"]
obj
# 通过赋值的方式直接修改索引

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [18]:
data = {"state":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
        "year":[2000,2001,2002,2001,2001,2002],
        "pop":[1.5,1.7,3.6,2.4,2.9,3.9]}
print(data)
frame = pd.DataFrame(data)
frame

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.9]}

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2001  2.9
5  Nevada  2002  3.9

DataFrame是表格型的数据结构，每列可以是不同的值类型（数值，字符串，布尔值等），具有行索引和列索引

In [19]:
print(frame.head(),"\n",
      frame.tail())
# 打印前五和后五行
from IPython.display import display
display(frame.head())
# 在jupyter环境下print会变成纯文本，display会保留dataframe原有的html格式

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2001  2.9
     state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2001  2.9
5  Nevada  2002  3.9

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2001  2.9

In [20]:
display(pd.DataFrame(data,columns=["year","state","pop"]),
        pd.DataFrame(columns=["year","state","pop"]))

# 指定行顺序

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2001  Nevada  2.9
5  2002  Nevada  3.9

Empty DataFrame
Columns: [year, state, pop]
Index: []

In [21]:
frame2 = pd.DataFrame(data,columns=["year","state","pop","debt"])
display(frame2)
display(frame2.columns)
# 若传入列在数据集中不存在，则生成缺失值

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2001  Nevada  2.9  NaN
5  2002  Nevada  3.9  NaN

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [22]:
frame2["state"]
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2001
5    2002
Name: year, dtype: int64

python代码的语法糖，两行代码取出的数据一模一样，均为将Dataframe中单独一列取出成为一个一维的series，但二者的底层调用和工程规范上不一致
frame2["state]是字典式索引
frame2.year是属性访问
优先使用字典式索引

In [23]:
frame2.loc[1]
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

两行代码均为从数据表切出某行数据
location
loc[1]从最左侧索引列index取出名字为1的行
integer location（整数位置）
iloc[2]从内存中取出第3位的行

In [24]:
frame2["debt"] = 16.5 #为空的debt列赋值
display(frame2)
np.random.seed()
frame2["debt"] = np.random.randn(len(frame2))
display(frame2)
frame2["debt"] = np.arange(6.) #附带
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2001  Nevada  2.9  16.5
5  2002  Nevada  3.9  16.5

   year   state  pop      debt
0  2000    Ohio  1.5  0.197355
1  2001    Ohio  1.7  1.271041
2  2002    Ohio  3.6 -1.451002
3  2001  Nevada  2.4  0.392136
4  2001  Nevada  2.9  0.245623
5  2002  Nevada  3.9  0.083669

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2001  Nevada  2.9   4.0
5  2002  Nevada  3.9   5.0

In [25]:
val = pd.Series([-1.2,-1.5,-1.7],index = ["two","four","five"])
frame2["debt"] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2001  Nevada  2.9   NaN
5  2002  Nevada  3.9   NaN

In [26]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2001  Nevada  2.9   NaN    False
5  2002  Nevada  3.9   NaN    False

In [27]:
del frame2['x']
frame2
# 删除列

KeyError: 'x'

In [ ]:
pop = {"Ohio":{2001:2.4,2002:2.9},
    "Nevada":{2000:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

      Ohio  Nevada
2001   2.4     1.7
2002   2.9     3.6
2000   NaN     1.5

另一种数据形式为嵌套字典
将嵌套字典传给Dataframe，则外层字典的键为列，内层键为行索引

In [ ]:
frame3.T
# 转置

        2001  2002  2000
Ohio     2.4   2.9   NaN
Nevada   1.7   3.6   1.5

In [ ]:
frame3

      Ohio  Nevada
2001   2.4     1.7
2002   2.9     3.6
2000   NaN     1.5

In [ ]:
pd.DataFrame(pop,index=[2001,2002,2003])
# 手动修改索引

      Ohio  Nevada
2001   2.4     1.7
2002   2.9     3.6
2003   NaN     NaN

In [ ]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2001   2.4     1.7
2002   2.9     3.6

frame3["Ohio"][:-1]将俄亥俄州列取出，去掉最后一行
通过pandas连接

In [ ]:
frame3.index.name = "year"
frame3.columns.name = "state"
display(frame3)
# 设置dataframe的列和栏name属性也可显示

state  Ohio  Nevada
year
2001    2.4     1.7
2002    2.9     3.6
2000    NaN     1.5

In [ ]:
display(frame3.values)
frame3.to_numpy()
# 返回value信息
display(frame2.to_numpy())

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, nan, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, nan, False],
       [2001, 'Nevada', 2.9, nan, False],
       [2002, 'Nevada', 3.9, nan, False]], dtype=object)

In [ ]:
obj = pd.Series(range(3),index=['a','b','c'])
display(obj)
index = obj.index
display(index)

a    0
b    1
c    2
dtype: int64

Index(['a', 'b', 'c'], dtype='str')

In [ ]:
index[1] = 'd'
# index的对象不可变，保证index对象在多个数据结构中可安全共享

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))
display(labels)
obj2 = pd.Series([1.5,-2.5,0],index=labels)
display(obj2)
obj2.index is labels

Index([0, 1, 2], dtype='int64')

0    1.5
1   -2.5
2    0.0
dtype: float64

True

关于Series，index，columns
Series：为一维数组
index：行标签
columns：列标签
obj = pd.Seires([4,7,-5,3])，绑定了一套index0，1，2，3的数字编码，即series = values + index
index 行索引，左侧标签
columns 列名，本质上DataFrame为共享同一个index的Series，通过column提取对应Series的键（值）

In [ ]:
display(frame3)
frame3.columns
"Ohio" in frame3.columns
2003 in frame3.index

      Ohio  Nevada
2001   2.4     1.7
2002   2.9     3.6
2000   NaN     1.5

False

In [ ]:
pd.Index(["foo","foo","bar","bar"])
# index可包含重复标签

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

In [ ]:
display(obj)
obj2 = obj.reindex(["Bob","Bob","c","d","d"])
display(obj2)
# 通过reindex将obj行标签对应的series值取出，可重复

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

Bob    4.0
Bob    4.0
c      NaN
d      NaN
d      NaN
dtype: float64

append
连接另一个Index对象，产生一个新的Index
difference
计算差集，并得到一个Index
intersection
计算交集
union
计算并集
isin
计算一个指示各值是否都包含在参数集合中的布尔型数组
delete
删除索引i处的元素，并得到新的Index
drop
删除传入的值，并得到新的Index
insert
将元素插入到索引处，并得到新的Index
is_monotonic
当各元素均大于等于前一个元素时，返回True
is_unique
当Index没有重复值时，返回True
unique
计算Index中唯一值的数组

In [ ]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: str

In [ ]:
obj3.reindex(np.arange(6.),method="ffill")
# 对有序数据插值

0.0      blue
1.0      blue
2.0    purple
3.0    purple
4.0    yellow
5.0    yellow
dtype: str

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=['Ohio','Texas','California'])
display(frame)
# 生成0-9的连续数字，折叠为3x3的二维方块，维度必须匹配

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2 = frame.reindex(index=['a','b','c','d'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [ ]:
states = ['Texas','Utah','California']
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [ ]:
# 重新索引轴的方法2 axis轴 =0为index =1为columns
frame.reindex(states,axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [ ]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
display(obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop('c')
display(new_obj)
obj.drop(['d','c']) #返回一个新对象
# 不会修改obj,通过obj = obj.drop修改或obj.drop('c',inplace=True)

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
e    4.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index=["Ohio",'Colorado',"Utah","New York"],columns=['one','two','three','four'])
display(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(index=['Colorado','Ohio'])
data.drop(columns=['two'])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
display(obj)

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:

obj[1] 
obj[1,3]
# pandas已砍掉fallback机制，现在obj[1]只会查询index=2的值而不会返回物理位置为2的值

KeyError: 1

In [ ]:
obj.loc[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj1[[0, 1, 2]]
obj2.loc[['a','b']]

a    1
b    2
dtype: int64

In [ ]:
obj1.iloc[[0,1,2]]
obj2.iloc[[0,1,2]]
# 由于 loc 运算符仅通过标签索引，因此还有一个 iloc 运算符，它仅通过整数索引，以保持一致性，无论索引是否包含整数

a    1
b    2
c    3
dtype: int64

In [ ]:
obj2.loc[['b','c']] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorrado','Utah','New York'],columns=['one','two','three','four'])
data

           one  two  three  four
Ohio         0    1      2     3
Colorrado    4    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

In [ ]:
data['two']
data[:2] #index
data[data['three'] > 5]
data < 5
data[data < 5] = 0
data

           one  two  three  four
Ohio         0    0      0     0
Colorrado    0    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

In [ ]:
display(data)
data.loc["Colorrado"]
data.loc[['Colorrado','New York']]
data.loc[['Colorrado'],['two','three']]

           one  two  three  four
Ohio         0    0      0     0
Colorrado    0    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

           two  three
Colorrado    5      6

In [ ]:
display(data)
data.index.name = 'city'
data.iloc[2]
display(data)
data.iloc[2,[3,0,1]]

           one  two  three  four
city
Ohio         0    0      0     0
Colorrado    0    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

           one  two  three  four
city
Ohio         0    0      0     0
Colorrado    0    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

four    11
one      8
two      9
Name: Utah, dtype: int64

In [ ]:
data.loc[:"Utah","two"]
data.iloc[:,:3][data.three > 10] #[:,:3]切出前三列，第三列的值>10

          one  two  three
city
New York   12   13     14

In [ ]:
data.loc[data["four"] > 1,"four"] = 10
data.drop('fout',axis=1)

           one  two  three  four
city
Ohio         0    0      0     0
Colorrado    3    3      3    10
Utah         3    3      3    10
New York     3    3      3    10

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
                index=["a", "c", "e", "f", "g"])
display(s1,s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1 + s2
# 标签位置不重叠的地方为缺失值

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),  
                index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
display(df1,df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
df1 + df2
df3 = df1 + df2
display(df3)
df3.loc['Ohio','b']

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

np.float64(3.0)

In [ ]:
display(df1)
display(df1.add(df2))
df1.add(df2,fill_value=0)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
      columns=list("abcd"))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))

df2.loc[1, "b"] = np.nan
df2
df2 + df1
df1.add(df2,fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
arr = np.arange(12.).reshape(3,4)
display(arr)

display(arr[0])
arr - arr[0]

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

array([0., 1., 2., 3.])

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]
display(frame,series)
frame - series

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
series3 = frame["d"]
series3
frame.sub(series3,axis=0) #subtraction 减法 匹配行索引，并在列上进行广播

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [ ]:
frame =  pd.DataFrame(np.random.standard_normal((4,3)),columns=("b","d","e"),index=["Utah", "Ohio", "Texas", "Oregon"])
frame2 = frame
frame2["e"] = 'a'
frame2

               b         d  e
Utah    1.028923  0.203761  a
Ohio    1.672369  0.543943  a
Texas   0.599436  0.298804  a
Oregon  0.278729  0.012534  a

.loc,.iloc先行后列
data[0:3]行优先
data["city"]列优先
单取一列直接写：data["列名"] （像字典查 Key）

范围取行用切片：data[0:5] （像列表切片段）

行列交叉必用轴：data.loc[行, 列] （像地图找坐标）

In [ ]:
frame =  pd.DataFrame(np.random.standard_normal((4,3)),columns=("b","d","e"),index=["Utah", "Ohio", "Texas", "Oregon"])
frame
np.abs(frame) #np的绝对值函数

               b         d         e
Utah    0.770884  1.192530  0.272263
Ohio    0.054115  0.101188  0.023024
Texas   2.219868  0.291048  0.266779
Oregon  0.257135  1.410716  1.613854

In [ ]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

b    2.477004
d    1.701763
e    1.880633
dtype: float64

函数 f （计算一个 Series 的最大值和最小值之差）对 frame 中的每一列都调用一次。结果是一个 Series，其索引为 frame 的列。

In [ ]:
display(frame)
frame.apply(f1,axis="columns")
# 按行最大减最小

               b         d         e
Utah    0.770884  1.192530  0.272263
Ohio   -0.054115 -0.101188 -0.023024
Texas   2.219868 -0.291048 -0.266779
Oregon -0.257135  1.410716  1.613854

Utah      0.920267
Ohio      0.078164
Texas     2.510916
Oregon    1.870989
dtype: float64

In [ ]:
def f2(x):
    return pd.Series([x.min(),x.max()],index=["mix","max"])
display(frame)
frame.apply(f2)

               b         d         e
Utah    0.770884  1.192530  0.272263
Ohio   -0.054115 -0.101188 -0.023024
Texas   2.219868 -0.291048 -0.266779
Oregon -0.257135  1.410716  1.613854

            b         d         e
mix -0.257135 -0.291048 -0.266779
max  2.219868  1.410716  1.613854

In [ ]:
def my_format(x):
    return f"{x:.2f}"
display(frame)
frame.map(my_format)
# map 方法用于应用逐元素函数

               b         d         e
Utah    0.770884  1.192530  0.272263
Ohio   -0.054115 -0.101188 -0.023024
Texas   2.219868 -0.291048 -0.266779
Oregon -0.257135  1.410716  1.613854

            b      d      e
Utah     0.77   1.19   0.27
Ohio    -0.05  -0.10  -0.02
Texas    2.22  -0.29  -0.27
Oregon  -0.26   1.41   1.61

In [ ]:
display(obj)
obj = pd.Series(np.arange(4),index=['d','a','b','c'])
obj.sort_index(axis=0) #通过sort_index对数据集按行或者列进行顺序排序

d    0
a    1
b    2
c    3
dtype: int64

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
from numpy import reshape


frame = pd.DataFrame(np.arange(8).reshape(2,4),index=['three','one'],columns=['d','a','b','c'])
display(frame)
display(frame.sort_index()) #行排序
display(frame.sort_index(axis='columns')) #列排序
display(frame.sort_values)

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

<bound method DataFrame.sort_values of        d  a  b  c
three  0  1  2  3
one    4  5  6  7>

In [ ]:
frame.sort_index(axis='columns',ascending=False) #使用降序排列

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [ ]:
obj
obj = pd.Series([4,7,-3,2])
obj
obj.sort_values() #对Seires按照值排序

2   -3
3    2
0    4
1    7
dtype: int64

In [ ]:
obj = pd.Series([4,np.nan,np.nan,-3,2])
obj.sort_values() #空值默认排到最后
obj.sort_values(na_position="first") #空值默认排到开头

1    NaN
2    NaN
3   -3.0
4    2.0
0    4.0
dtype: float64

In [ ]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
display(frame)
display(frame.sort_values("b"))

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [ ]:
frame.sort_values(['a','b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [ ]:
obj = pd.Series([7,-5,7,4,2,0,4])
display(obj)
display(obj.rank()) #rank按照排名进行排序

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [ ]:
obj.rank(method='first')
# 按照出现顺序排名，不会出现相同排名而按照出现顺序对相同排名排列

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [ ]:
obj
obj.rank(ascending=False)
# 按照降序排列

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [ ]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                      'c':[-2,5,8,-2.5]})
display(frame)
display(frame.rank(axis=1))
# 按列排序，根据每列大小默认从一开始

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [ ]:
obj = pd.Series(np.arange(5),index=["a", "a", "b", "b", "c"])
display(obj)

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [ ]:
obj.index.is_unique
# index的is_unique属性索引标签是否唯一

False

In [ ]:
display(obj['a'])

a    0
a    1
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.standard_normal((5,3)),index=['a','a','b','b','c'])
display(df)
df.loc[["a","b"],0] #.loc先行后列

          0         1         2
a -0.622681  1.400988 -0.665414
a  0.012726 -0.283108  1.314134
b  1.645113  0.814720 -1.061926
b -0.652770  0.732811 -0.729938
c  1.509719  0.938344 -0.441436

a   -0.622681
a    0.012726
b    1.645113
b   -0.652770
Name: 0, dtype: float64

In [ ]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
display(df.sum(axis=1))
display(df.sum()) 
#sum默认返回列的总和,axis=0

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

one    9.25
two   -5.80
dtype: float64

In [ ]:
df.sum(axis=0,skipna=False)
#skipna=False：只要某列里有 NaN，该列的和就是 NaN
# axis=0：按列聚合

one   NaN
two   NaN
dtype: float64

In [ ]:
display(df.sum)
display(df.sum(axis='index',skipna=False))
df.sum(axis='columns',skipna=False)

<bound method DataFrame.sum of     one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3>

one   NaN
two   NaN
dtype: float64

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [ ]:
df.mean(axis="columns")
#平均值

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [ ]:
display(df)
df.idxmax()
# 默认按列，返回每列最大值的行标签，跳过nan

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

one    b
two    d
dtype: str

In [ ]:
df.cumsum()
# 累计，默认按列，跳过na

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [ ]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
uniques = obj.unique()
uniques
# 提取一维Series中的唯一值

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [ ]:
obj.value_counts()
# 计算频率

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [42]:
pd.Series(obj.to_numpy()).value_counts(sort=False)
# 把 obj 里的数据转成 NumPy 数组后，统计每个不同值的出现次数,并且不按频数重新排序

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [43]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [45]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [47]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: str

In [48]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

In [49]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                    "Qu2": [2, 3, 1, 2, 3],
                    "Qu3": [1, 5, 2, 4, 4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [ ]:
data['Qu1'].value_counts().sort_index()
# value_counts()：看谁出现了几次；sort_index()：把统计结果按类别编号顺序排好

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [53]:
result = data.apply(pd.Series.value_counts).fillna(0)
result

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0