In [1]:
import pandas as pd
import numpy as np

数据加载、存储和文件格式

In [2]:
cat examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [3]:
df = pd.read_csv("examples/ex1.csv")
display(df)
# 按逗号分隔可通过read_csv读入为DataFrame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [4]:
cat examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [5]:
pd.read_csv("examples/ex2.csv",header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [6]:
pd.read_csv('examples/ex2.csv',names=['a','b','c','d','message'])
# 自定义列名

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
cat examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [8]:
parsed = pd.read_csv('examples/csv_mindex.csv',index_col=['key1','key2'])
display(parsed)
# 返回一个 DataFrame，但它的行索引不再是默认数字，而是一个两层的 MultiIndex

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [9]:
cat examples/ex3.txt
# 无固定的分隔符，使用空格等分隔字段，需要使用正则表达式进行分隔

SyntaxError: invalid syntax (1453625345.py, line 1)

In [ ]:
result = pd.read_csv('examples/ex3.txt')
display(result)
result =  pd.read_csv('examples/ex3.txt',sep='\s+')
display(result)

               A         B         C
0  aaa -0.264438 -1.026059 -0.619500
1  bbb  0.927272  0.302904 -0.032399
2  ccc -0.264273 -0.386314 -0.217601
3  ddd -0.871858 -0.348382  1.100491

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [ ]:
cat examples/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [ ]:
pd.read_csv('examples/ex4.csv',skiprows=[0,2,3])
# 跳过文件指定行

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
cat examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [ ]:
result = pd.read_csv('examples/ex5.csv')
display(result) #缺失值默认用Nan
pd.isna(result)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [ ]:
result = pd.read_csv('examples/ex5.csv',na_values=['NULL'])
result
# na_values=['NULL']
# 告诉 pandas：
# 如果某个单元格内容是字符串 "NULL"，不要把它当普通字符串保存，
# 而要把它识别成缺失值 NaN

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:
result2 = pd.read_csv("examples/ex5.csv",keep_default_na=False)
# 让 pandas 不要把像 NA、NULL、NaN 这类默认字符串自动当成缺失值
display(result2)
result2.isna()

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [ ]:
display(result)
result3 = pd.read_csv('examples/ex5.csv',keep_default_na=False,na_values=['NA'])
display(result3)
display(result3.isna())

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [ ]:
sentinels = {'message':['foo','NA'],'something':['two']}
display(sentinels)
pd.read_csv('examples/ex5.csv',keep_default_na=False,na_values=sentinels)
# 指定缺失值

{'message': ['foo', 'NA'], 'something': ['two']}

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

In [ ]:
pd.options.display.max_rows = 10
result = pd.read_csv('examples/ex6.csv')
result
# 展示时最多显示 10 行

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [ ]:
pd.read_csv('examples/ex6.csv',nrows=5)
# 只读取少量行

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [ ]:
chunker=pd.read_csv('examples/ex6.csv',chunksize=1000)
tot = pd.Series([],dtype='int64')
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(),fill_value=0)

tot = tot.sort_values(ascending=False)
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

这段代码的核心思想是：不一次性把整个大文件读进内存，而是分块读取，每读一块就统计一次 key 列频数，最后把所有块的统计结果累加起来。

In [ ]:
data = pd.read_csv('examples/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:
data.to_csv('examples/out.csv')
!cat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [ ]:
import sys
data.to_csv(sys.stdout,sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [ ]:
data.to_csv(sys.stdout,na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [ ]:
data.to_csv(sys.stdout,index=False,header=False)
# 写入禁用行列标签

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [ ]:
data.to_csv(sys.stdout,index=False,columns=['a'])
# 写入指定列

a
1
5
9

In [ ]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [ ]:
pd.read_csv('examples/ex7.csv')

   a  b  c
0  1  2  3
1  1  2  3

In [ ]:
import csv
f = open('examples/ex7.csv')
reader = csv.reader(f)
for line in reader:
    print(line)
# 有些格式异常的文件，先用 csv.reader 看原始结构更容易理解问题

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [ ]:
with open('examples/ex7.csv') as f:
    lines = list(csv.reader(f))
header,values = lines[0],lines[1:]
data_dict = {h:v for h,v in zip(header,zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [ ]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [ ]:
asjson = json.dumps(result)
asjson
# 把 result 转成 JSON 格式的字符串，并把结果保存到 asjson 里

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [ ]:
siblings = pd.DataFrame(result['siblings'],columns=['name','age'])
display(siblings)

    name  age
0  Scott   34
1  Katie   42

In [ ]:
!cat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [ ]:
data.to_json(sys.stdout)

{"something":{"0":"one","1":"two","2":"three"},"a":{"0":1,"1":5,"2":9},"b":{"0":2,"1":6,"2":10},"c":{"0":3.0,"1":null,"2":11.0},"d":{"0":4,"1":8,"2":12},"message":{"0":null,"1":"world","2":"foo"}}

In [ ]:
data.to_json(sys.stdout,orient='records')
# 把 DataFrame 按“每行一条记录”的方式转成 JSON，并直接打印出来

[{"something":"one","a":1,"b":2,"c":3.0,"d":4,"message":null},{"something":"two","a":5,"b":6,"c":null,"d":8,"message":"world"},{"something":"three","a":9,"b":10,"c":11.0,"d":12,"message":"foo"}]

In [ ]:
tables = pd.read_html("examples/fdic_failed_bank_list.html")
len(tables)

1

In [ ]:
failures = tables[0] #取出表1
failures.tail()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014"
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002"
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003"
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005"
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005"

In [ ]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps.dt.year.value_counts()
# 把关闭日期转成时间格式，取出年份，再数每年有多少条关闭记录

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

In [ ]:
<INDICATOR>
  <INDICATOR_SEQ>373889</INDICATOR_SEQ>
  <PARENT_SEQ></PARENT_SEQ>
  <AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
  <INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
  <DESCRIPTION>Percent of the time that escalators are operational
  systemwide. The availability rate is based on physical observations performed
  the morning of regular business days only. This is a new indicator the agency
  began reporting in 2009.</DESCRIPTION>
  <PERIOD_YEAR>2011</PERIOD_YEAR>
  <PERIOD_MONTH>12</PERIOD_MONTH>
  <CATEGORY>Service Indicators</CATEGORY>
  <FREQUENCY>M</FREQUENCY>
  <DESIRED_CHANGE>U</DESIRED_CHANGE>
  <INDICATOR_UNIT>%</INDICATOR_UNIT>
  <DECIMAL_PLACES>1</DECIMAL_PLACES>
  <YTD_TARGET>97.00</YTD_TARGET>
  <YTD_ACTUAL></YTD_ACTUAL>
  <MONTHLY_TARGET>97.00</MONTHLY_TARGET>
  <MONTHLY_ACTUAL></MONTHLY_ACTUAL>
</INDICATOR>

SyntaxError: invalid syntax (2722320822.py, line 1)

读取Excel文件
pandas 也支持使用 pandas.ExcelFile 类或 pandas.read_excel 函数读取存储在 Excel 2003（及更高版本）文件中的表格数据。内部，这些工具分别使用 xlrd 和 openpyxl 插件包来读取旧式 XLS 文件和较新的 XLSX 文件。这些必须使用 pip 或 conda 单独于 pandas 进行安装

In [11]:
import pandas as pd
xlsx = pd.ExcelFile("examples/ex1.xlsx")
xlsx.sheet_names

['Sheet1']

In [ ]:
xlsx.parse(sheet_name='Sheet1')
# 从 Excel 文件对象里，把 Sheet1 这个工作表读成 DataFrame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [14]:
frame = pd.read_excel("examples/ex1.xlsx",sheet_name="Sheet1")
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [ ]:
frame = pd.DataFrame({'a':np.random.standard_normal(100)}) #生成100个标准正态分布随机数，存入列名为a的DataFrame中
store = pd.HDFStore('examples/mydata.h5') #创建一个HDF5文件
store['obj1'] = frame #将frame存进去，键名为obj2
store['obj1_col'] = frame['a']
# 把 frame['a'] 这一列单独存进去，键名是 "obj1_col"
store

<class 'pandas.HDFStore'>
File path: examples/mydata.h5

在 pandas 里，字典的：

key -> 列名
value -> 这一列的数据

In [16]:
store['obj1']

           a
0   0.020215
1  -0.991233
2   0.845924
3   0.556812
4  -0.858187
..       ...
95 -0.546581
96  0.312559
97  0.243333
98 -0.203667
99  0.185284

[100 rows x 1 columns]

In [17]:
store.put('obj2',frame,format='table')
store.select('obj2',where=['index>=10 and index <= 15'])

           a
10 -0.616119
11  1.712144
12 -0.884311
13 -1.026553
14 -2.004298
15  1.384602

In [18]:
import os

In [19]:
os.remove("examples/mydata.h5")

In [20]:
import requests

In [ ]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp.raise_for_status()
# 检查 HTTP 请求是否成功，如果失败就直接报错
resp

In [22]:
data =resp.json()
data[0]["title"]

'TST: add test for Series constructor dtype enforcement from Series input (#59060)'

In [23]:
issues = pd.DataFrame(data,columns=['number','title','labels','state'])
issues

,number,title,labels,state
0,64706,TST: add test for Series constructor dtype enf...,[],open
1,64705,TST: add test for FloatingArray mean with skip...,[],open
2,64704,convert_dtypes corrupts column shape on sliced...,[],open
3,64703,Hosting of the pandas website and documentation,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
4,64702,BUG: Wrong dataframe data after `convert_dtypes`,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
5,64701,DEPR: Series.dt.freq returning a string instea...,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
6,64700,TST: add regression test for iterrows datetime...,[],open
7,64699,"DEPR: isinstance(obj, DateOffset) for non-Date...","[{'id': 53181044, 'node_id': 'MDU6TGFiZWw1MzE4...",open
8,64697,TST: add test for CategoricalIndex of Interval...,[],open
9,64695,BUG: raise on .loc setitem with integer key on...,[],open
10,64694,BUG: raise `TypeError` on comparisons involvin...,[],open
11,64691,PERF: use lookup instead of hash_inner_join fo...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
12,64690,BLD: use idiomatic meson dependency pattern fo...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
13,64689,BUG: fix MultiIndex loc with np.datetime64 on ...,[],open
14,64688,TST: add test for tz-aware datetime column exp...,[],open
15,64687,TST: add test for .info() dtype after datetime...,[],open
16,64686,TST: add test for string slice with sub-second...,[],open
17,64685,BUG: fix Index.drop failing to match NA values...,[],open
18,64682,DOC: fix incomplete sentence in Styler docstring,[],open
19,64681,DOC: incomplete sentence in Styler docstring,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
20,64680,BUG: skip test_legacy_files when legacy .h5 fi...,[],open
21,64679,DEPR: infer_freq/inferred_freq returning str i...,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
22,64678,DEPR: warn on silent dtype changes during seti...,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
23,64676,CLN: add .venv to .gitignore,[],open
24,64675,DEPR: deprecate convert_dates and keep_default...,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
25,64673,"DEPR: deprecate fastparquet engine, engine key...","[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
26,64672,PERF: fix catastrophic regex backtracking in r...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
27,64671,PERF: Use _global_config directly when accessi...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
28,64669,PERF: Micro-optimizations in C extension sourc...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
29,64667,BUG: Fix empty cells when hiding index in Styl...,[],open

In [24]:
import sqlite3

In [26]:
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""

In [27]:
con = sqlite3.connect("mydata.sqlite")
con.execute(query)

In [28]:
con.commit

In [ ]:
data = [('Atlanta','Georgia',1.25,6),
        ("Tallahassee","Florida",2.6,3),
        ("Sacramento","California",1.7,5)]
stmt = "INSERT INTO test VALUES(?,?,?,?)"
# SQL 插入语句
con.executemany(stmt,data)
# 批量执行插入
con.commit()

In [31]:
cursor = con.execute("SELECT * FROM test")
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [33]:
import sqlalchemy as sqala
db = sqala.create_engine("sqlite:///mydata.sqlite")
pd.read_sql("SELECT * FROM test",db)

Empty DataFrame
Columns: [a, b, c, d]
Index: []