层级索引

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.Series(np.random.uniform(size=9),index=[['a','a','a','b','b','c','c','d','d'],
                                                  [1,2,3,1,3,1,2,2,3]])

In [4]:
display(data)

a  1    0.530317
   2    0.470191
   3    0.288267
b  1    0.129030
   3    0.736255
c  1    0.282186
   2    0.815334
d  2    0.030914
   3    0.948241
dtype: float64

In [5]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data['b']

1    0.129030
3    0.736255
dtype: float64

In [7]:
data['b':'d']

b  1    0.129030
   3    0.736255
c  1    0.282186
   2    0.815334
d  2    0.030914
   3    0.948241
dtype: float64

In [8]:
data.loc[:,2]
# 取出data中所有行，列名为2的列

a    0.470191
c    0.815334
d    0.030914
dtype: float64

In [9]:
data.unstack()
# 通过unstack()将data重新排列为DataFrame

          1         2         3
a  0.530317  0.470191  0.288267
b  0.129030       NaN  0.736255
c  0.282186  0.815334       NaN
d       NaN  0.030914  0.948241

In [10]:
datatest = data.unstack()
datatest

          1         2         3
a  0.530317  0.470191  0.288267
b  0.129030       NaN  0.736255
c  0.282186  0.815334       NaN
d       NaN  0.030914  0.948241

In [11]:
display(datatest.stack())
# 通过.stack()逆操作

a  1    0.530317
   2    0.470191
   3    0.288267
b  1    0.129030
   2         NaN
   3    0.736255
c  1    0.282186
   2    0.815334
   3         NaN
d  1         NaN
   2    0.030914
   3    0.948241
dtype: float64

In [12]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                     index=[['a','a','b','b'],[1,2,1,2]],
                     columns=[['Ohio','Ohio','Colorado'],
                              ['Green','Red','Green']])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [13]:
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [14]:
frame.index.nlevels

2

In [15]:
frame["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

重新排序和排序级别

In [16]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [17]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [18]:
display(frame)
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [19]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

按级别进行的摘要统计

In [20]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [21]:
frame.groupby(level='key2').sum()
# 按照行索引中名字叫 key2 的那一层来分组，然后对每组数据求和

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

使用 DataFrame 的列进行索引

In [22]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                       "c": ["one", "one", "one", "two", "two",
                             "two", "two"],
                       "d": [0, 1, 2, 0, 1, 2, 3]})

In [23]:
display(frame)
frame2 = frame.set_index(['c','d'])
# 通过set_index函数使用一或多个列建立新DataFrame
frame2

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [24]:
frame.set_index(['c','d'],drop=False)
# 默认移除，使用drop=False保留

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [25]:
display(frame2)
frame2.reset_index()
# 通过reset_index将层级索引移入列中

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

合并数据集

In [26]:
df1 = pd.DataFrame({"key":['b','b','a','c','a','a','b'],
                    'data1':pd.Series(range(7),dtype="Int64")})
df2 = pd.DataFrame({"key":['a','b','d'],
                    "data2":pd.Series(range(3),dtype="Int64")})
display(df1,df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

  key  data2
0   a      0
1   b      1
2   d      2

In [27]:
pd.merge(df1,df2)
# pandas.merge 会使用重叠的列名作为键

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [28]:
pd.merge(df1,df2,on="key")
# 建议明确指定列后连接

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [29]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                     "data1": pd.Series(range(7), dtype="Int64")})

df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                     "data2": pd.Series(range(3), dtype="Int64")})
display(df3,df4)

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

  rkey  data2
0    a      0
1    b      1
2    d      2

In [30]:
pd.merge(df3,df4,left_on='lkey',right_on='rkey')
# 抹去了c，d值和相关数据，pandas.merge默认为键的交集

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [31]:
display(df1,df2)
pd.merge(df1,df2,how="outer")

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

  key  data2
0   a      0
1   b      1
2   d      2

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [32]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey",how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [33]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                     "data1": pd.Series(range(6), dtype="Int64")})

df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                     "data2": pd.Series(range(5), dtype="Int64")})
display(df1,df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [34]:
pd.merge(df1,df2,on="key",how="left")
# 多对多合并会形成匹配键的笛卡尔积

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [35]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                      "key2": ["one", "two", "one"],
                      "lval": pd.Series([1, 2, 3], dtype='Int64')})

right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                       "key2": ["one", "one", "one", "two"],
                       "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})
display(left,right)
pd.merge(left,right,on=['key1','key2'],how='outer')

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [36]:
pd.merge(left,right,on='key1')

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [37]:
pd.merge(left, right, on="key1", suffixes=("_left", "_right"))
# 当两个表里有同名列时，merge 后给重名列自动加后缀，避免冲突

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

基于索引合并

In [38]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                       "value": pd.Series(range(6), dtype="Int64")})
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])
display(left1,right1)

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

   group_val
a        3.5
b        7.0

In [39]:
pd.merge(left1,right1,left_on='key',right_index=True)
# 将右表的索引当成键与左表匹配，未写how默认inner，left_on指定某列作为键

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [40]:
lefth = pd.DataFrame({"key1": ["Ohio", "Ohio", "Ohio",
                                "Nevada", "Nevada"],
                       "key2": [2000, 2001, 2002, 2001, 2002],
                       "data": pd.Series(range(5), dtype="Int64")})

In [41]:
display(lefth)

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [42]:
righth_index = pd.MultiIndex.from_arrays(
    [
        ['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],
        [2001,2000,2000,2000,2001,2002]
    ]
)
righth = pd.DataFrame({"event1":pd.Series([0,2,4,6,8,10],dtype="Int64",
                                          index=righth_index),
                                          "event2": pd.Series([1, 3, 5, 7, 9, 11], dtype="Int64",
                                        index=righth_index)})

In [43]:
display(lefth,righth)

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [44]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,
         )

     key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
3  Nevada  2001     3       0       1
2    Ohio  2002     2      10      11

In [45]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,
         how = "outer")

     key1  key2  data  event1  event2
4  Nevada  2000  <NA>       2       3
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11

In [46]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                      index=["a", "c", "e"],
                      columns=["Ohio", "Nevada"]).astype("Int64")
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                       index=["b", "c", "d", "e"],
                       columns=["Missouri", "Alabama"]).astype("Int64")
display(left2,right2)

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [47]:
pd.merge(left2,right2,left_index=True,right_index=True)
# 使用两边的索引合并

   Ohio  Nevada  Missouri  Alabama
c     3       4         9       10
e     5       6        13       14

In [48]:
left2.join(right2,how="outer")
# join默认左连接

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [49]:
display(left1,right1)
left1.join(right1,on="key")
# join也支持调用DataFrame的某列做连接

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

   group_val
a        3.5
b        7.0

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [50]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                        index=["a", "c", "e", "f"],
                        columns=["New York", "Oregon"])
display(another)

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [51]:
display(left2,right2)

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [52]:
left2.join([right2,another])
# 把 right2 和 another 这两个表，一起按索引连接到 left2 上

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [53]:
left2.join([right2,another],how="outer")

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
b  <NA>    <NA>         7        8       NaN     NaN
c     3       4         9       10       9.0    10.0
d  <NA>    <NA>        11       12       NaN     NaN
e     5       6        13       14      11.0    12.0
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

沿着轴连接

In [54]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
np.concatenate([arr,arr],axis=1)
# 在numpy中，只认轴编号。
# 二维数组中：
# axis=0 表示行轴
# axis=1 表示列轴

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [56]:
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")

s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")

s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")

display(s1,s2,s3)

a    0
b    1
dtype: Int64

c    2
d    3
e    4
dtype: Int64

f    5
g    6
dtype: Int64

In [57]:
pd.concat([s1,s2,s3])
# 把 s1、s2、s3 这几个对象沿着默认方向拼接起来。
# 如果 s1、s2、s3 是 Series，默认是按 行方向 拼，也就是上下接起来

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [58]:
pd.concat([s1,s2,s3],axis=1)

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [61]:
result = pd.concat([s1,s2,s3],keys=['one','two','three'])
result
# 通过keys在连接轴上加一个层次索引

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: Int64

In [62]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"],
                    columns=["one", "two"])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"],
                    columns=["three", "four"])
display(df1,df2)

   one  two
a    0    1
b    2    3
c    4    5

   three  four
a      5     6
c      7     8

In [63]:
pd.concat([df1,df2],axis="columns",keys=['level1','level2'])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

重叠数据的合并

In [64]:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
               index=["f", "e", "d", "c", "b", "a"])

b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
               index=["a", "b", "c", "d", "e", "f"])
display(a,b)

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [67]:
np.where(pd.isna(a),b,a)
# 如果 a 这个位置是缺失值，就用 b 的值；否则就用 a 自己的值
# np.where(condition, x, y)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [ ]:
a.combine_first(b)
# 优先用 a 的值，如果 a 缺失，就用 b 对应位置的值补上。

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

重塑和透视

stack

这会从数据中的列“旋转”或转换到行。

unstack

这将从行转换为列。

In [69]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                     index=pd.Index(["Ohio", "Colorado"], name="state"),
                     columns=pd.Index(["one", "two", "three"],
                     name="number"))

In [70]:
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [74]:
display(data.stack())
# 把列“压到行里去”

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [75]:
data.unstack()

number  state
one     Ohio        0
        Colorado    3
two     Ohio        1
        Colorado    4
three   Ohio        2
        Colorado    5
dtype: int64

In [77]:
s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")

s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")

data2 = pd.concat([s1, s2], keys=["one", "two"])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [79]:
data2.unstack()
# 将列转为行

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [85]:
# 堆叠操作默认会过滤掉缺失数据
display(data2.unstack().stack())
data2

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

将“长”格式转向“宽”格式

In [96]:
data = pd.read_csv("examples/macrodata.csv")

In [93]:
data.head()

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.37,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.54,139.6,3.50,5.2,180.007,2.31,1.19

In [94]:
data = data.loc[:, ["year", "quarter", "realgdp", "infl", "unemp"]]
data

     year  quarter    realgdp  infl  unemp
0    1959        1   2710.349  0.00    5.8
1    1959        2   2778.801  2.34    5.1
2    1959        3   2775.488  2.74    5.3
3    1959        4   2785.204  0.27    5.6
4    1960        1   2847.699  2.31    5.2
..    ...      ...        ...   ...    ...
198  2008        3  13324.600 -3.16    6.0
199  2008        4  13141.920 -8.79    6.9
200  2009        1  12925.410  0.94    8.1
201  2009        2  12901.504  3.37    9.2
202  2009        3  12990.341  3.56    9.6

[203 rows x 5 columns]

In [98]:
df = pd.DataFrame({"key": ["foo", "bar", "baz"],
                   "A": [1, 2, 3],
                    "B": [4, 5, 6],
                    "C": [7, 8, 9]})

In [99]:
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [ ]:
melted = pd.melt(df,id_vars='key')
melted
# 把 df 从“宽表”变成长表，并且把 key 这一列保留下来作为标识列

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [103]:
reshaped = melted.pivot(index="key", columns="variable",
                         values="value")
reshaped

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [ ]:
reshaped.reset_index()
# pivot 操作会根据用作行标签的列创建索引，因此我们可能需要使用 reset_index 将数据移回列中

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [107]:
pd.melt(df, id_vars="key", value_vars=["A", "B"])
#  保留 key，只把 A 和 B 变成长表

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [ ]:
pd.melt(df,value_vars=['A','B','C'])
# 不指定分组标识符

  variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [109]:
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [110]:
pd.melt(df, value_vars=["key", "A", "B"])

  variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6