数据聚合和分组操作

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame(
    {"key1" : ["a", "a", None, "b", "b", "a", None],
                    "key2" : pd.Series([1, 2, 1, 2, 1, None, 1],
                                       dtype="Int64"),
                    "data1" : np.random.standard_normal(7),
                    "data2" : np.random.standard_normal(7)}
)
df

  key1  key2     data1     data2
0    a     1  0.605962 -3.197993
1    a     2 -1.126528 -0.600208
2  NaN     1  1.302704 -0.024254
3    b     2 -1.825254  0.534924
4    b     1  0.965766  0.206916
5    a  <NA>  1.449857  0.368974
6  NaN     1  1.354600 -1.323313

In [3]:
grouped = df["data1"].groupby(df["key1"])
display(grouped)

In [4]:
grouped.mean()

key1
a    0.309763
b   -0.429744
Name: data1, dtype: float64

In [ ]:
means = df["data1"].groupby([df['key1'],df['key2']]).mean()
means

key1  key2
a     1       0.605962
      2      -1.126528
b     1       0.965766
      2      -1.825254
Name: data1, dtype: float64

In [6]:
means.unstack()

key2         1         2
key1
a     0.605962 -1.126528
b     0.965766 -1.825254

In [ ]:
states = np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])

years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

df.groupby([states,years])["data1"].mean()
# 加不加引号，取决于传进去的是“列名字符串”还是“变量”

CA  2005    0.161664
    2006    1.302704
OH  2005   -0.609646
    2006    1.160183
Name: data1, dtype: float64

In [9]:
df.groupby("key1").mean()

      key2     data1     data2
key1
a      1.5  0.309763 -1.143076
b      1.5 -0.429744  0.370920

In [11]:
df.groupby("key2").mean(numeric_only=True)

         data1     data2
key2
1     1.057258 -1.084661
2    -1.475891 -0.032642

In [ ]:
df.groupby(['key1','key2']).mean()
# 通过分组键传递

              data1     data2
key1 key2
a    1     0.605962 -3.197993
     2    -1.126528 -0.600208
b    1     0.965766  0.206916
     2    -1.825254  0.534924

In [17]:
df.groupby(['key1','key2'])[['data1','data2']].mean(numeric_only=True)

              data1     data2
key1 key2
a    1     0.605962 -3.197993
     2    -1.126528 -0.600208
b    1     0.965766  0.206916
     2    -1.825254  0.534924

In [ ]:
df.groupby(['key1','key2']).size()
# 按 key1 和 key2 分组，然后统计每组有多少行

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [21]:
display(df)

display(df.groupby("key1",dropna=False).size(),
        df.groupby(['key1','key2'],dropna=False).size()
)

  key1  key2     data1     data2
0    a     1  0.605962 -3.197993
1    a     2 -1.126528 -0.600208
2  NaN     1  1.302704 -0.024254
3    b     2 -1.825254  0.534924
4    b     1  0.965766  0.206916
5    a  <NA>  1.449857  0.368974
6  NaN     1  1.354600 -1.323313

key1
a      3
b      2
NaN    2
dtype: int64

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [ ]:
df.groupby('key1').count()
# 计算非空数量

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [24]:
for name , group in df.groupby("key1"):
    print(name)
    print(group)
# group返回对象支持迭代

a
  key1  key2     data1     data2
0    a     1  0.605962 -3.197993
1    a     2 -1.126528 -0.600208
5    a  <NA>  1.449857  0.368974
b
  key1  key2     data1     data2
3    b     2 -1.825254  0.534924
4    b     1  0.965766  0.206916

In [26]:
for (k1,k2) , group in df.groupby(["key1","key2"]):
    print((k1,k2))
    print(group)

('a', 1)
  key1  key2     data1     data2
0    a     1  0.605962 -3.197993
('a', 2)
  key1  key2     data1     data2
1    a     2 -1.126528 -0.600208
('b', 1)
  key1  key2     data1     data2
4    b     1  0.965766  0.206916
('b', 2)
  key1  key2     data1     data2
3    b     2 -1.825254  0.534924

In [28]:
pieces = {name:group for name,group in df.groupby('key1')}
pieces

{'a':   key1  key2     data1     data2
 0    a     1  0.605962 -3.197993
 1    a     2 -1.126528 -0.600208
 5    a  <NA>  1.449857  0.368974,
 'b':   key1  key2     data1     data2
 3    b     2 -1.825254  0.534924
 4    b     1  0.965766  0.206916}

In [ ]:
df.groupby("key1")["data1"]
df.groupby("key1")[["data2"]]
df["data1"].groupby(df["key1"])
df[["data2"]].groupby(df["key1"])

In [40]:
display(df)
df.groupby(['key1','key2'])[["data2"]].mean()
# 根据key1，key2分组，然后从data2中取值，双中括号代表取Dataframe

  key1  key2     data1     data2
0    a     1  0.605962 -3.197993
1    a     2 -1.126528 -0.600208
2  NaN     1  1.302704 -0.024254
3    b     2 -1.825254  0.534924
4    b     1  0.965766  0.206916
5    a  <NA>  1.449857  0.368974
6  NaN     1  1.354600 -1.323313

              data2
key1 key2
a    1    -3.197993
     2    -0.600208
b    1     0.206916
     2     0.534924

In [42]:
s_grouped = df.groupby(['key1','key2'])["data2"]
s_grouped.mean()

key1  key2
a     1      -3.197993
      2      -0.600208
b     1       0.206916
      2       0.534924
Name: data2, dtype: float64

In [44]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                       columns=["a", "b", "c", "d", "e"],
                       index=["Joe", "Steve", "Wanda", "Jill", "Trey"])
people

              a         b         c         d         e
Joe    1.245947 -1.411038  0.611510 -1.442972 -0.750737
Steve  1.032951 -1.802798 -0.913568 -0.711397 -0.994770
Wanda -0.434352  1.463390  2.309667  0.372105 -0.386077
Jill   0.044748  0.555696  0.255354 -0.131052  0.292225
Trey  -0.962735  0.558656 -1.550464 -0.054365  0.045265

In [45]:
mapping = {"a": "red", "b": "red", "c": "blue",
            "d": "blue", "e": "red", "f" : "orange"}

In [ ]:
# by_columns = people.groupby(mapping,axis=1)已弃用
by_columns = people.T.groupby(mapping)
by_columns.mean()
# groupby() 更标准的对象是“行”,通过转置将列变为行然后mapping

           Joe     Steve     Wanda      Jill      Trey
blue -0.415731 -0.812482  1.340886  0.062151 -0.802415
red  -0.305276 -0.588206  0.214320  0.297557 -0.119605

In [53]:
map_series = pd.Series(mapping)
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: str

In [54]:
people.T.groupby(map_series).count()

      Joe  Steve  Wanda  Jill  Trey
blue    2      2      2     2     2
red     3      3      3     3     3

In [55]:
people

              a         b         c         d         e
Joe    1.245947 -1.411038  0.611510 -1.442972 -0.750737
Steve  1.032951 -1.802798 -0.913568 -0.711397 -0.994770
Wanda -0.434352  1.463390  2.309667  0.372105 -0.386077
Jill   0.044748  0.555696  0.255354 -0.131052  0.292225
Trey  -0.962735  0.558656 -1.550464 -0.054365  0.045265

In [ ]:
people.groupby(len).sum()
# group允许传函数

          a         b         c         d         e
3  1.245947 -1.411038  0.611510 -1.442972 -0.750737
4 -0.917987  1.114352 -1.295110 -0.185417  0.337491
5  0.598598 -0.339408  1.396099 -0.339292 -1.380847

In [ ]:
key_list = ["one", "one", "one", "two", "two"]
people.groupby([len, key_list]).min()
# 根据名称长度和one‘two分组再计算最小值

              a         b         c         d         e
3 one  1.245947 -1.411038  0.611510 -1.442972 -0.750737
4 two -0.962735  0.555696 -1.550464 -0.131052  0.045265
5 one -0.434352 -1.802798 -0.913568 -0.711397 -0.994770

In [59]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"],
                                     [1, 3, 5, 1, 3]],
                                     names=["cty", "tenor"])
display(columns)

MultiIndex([('US', 1),
            ('US', 3),
            ('US', 5),
            ('JP', 1),
            ('JP', 3)],
           names=['cty', 'tenor'])

In [62]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns=columns)
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0      0.130625  0.597447  2.341925 -0.393478 -0.624961
1      0.828175 -1.672666  1.155999 -0.728935 -1.388686
2      1.132431  0.196040 -1.008377  0.133344 -0.248667
3     -2.417541  0.349295 -2.507349  0.939619 -0.507605

In [67]:
hier_df.stack().unstack()

cty          US                            JP
tenor         1         3         5         1         3   5
0      0.130625  0.597447  2.341925 -0.393478 -0.624961 NaN
1      0.828175 -1.672666  1.155999 -0.728935 -1.388686 NaN
2      1.132431  0.196040 -1.008377  0.133344 -0.248667 NaN
3     -2.417541  0.349295 -2.507349  0.939619 -0.507605 NaN

In [68]:
hier_df.T.groupby(level='cty').count()

     0  1  2  3
cty
JP   2  2  2  2
US   3  3  3  3

In [69]:
df

  key1  key2     data1     data2
0    a     1  0.605962 -3.197993
1    a     2 -1.126528 -0.600208
2  NaN     1  1.302704 -0.024254
3    b     2 -1.825254  0.534924
4    b     1  0.965766  0.206916
5    a  <NA>  1.449857  0.368974
6  NaN     1  1.354600 -1.323313

In [70]:
grouped = df.groupby('key1')
grouped.sum()

      key2     data1     data2
key1
a        3  0.929290 -3.429227
b        3 -0.859488  0.741840

In [ ]:
grouped["data1"].nsmallest(2)
# 对groupd的各个分组的data1 ,取最小的两个值

key1
a     1   -1.126528
      0    0.605962
b     3   -1.825254
      4    0.965766
Name: data1, dtype: float64

In [74]:
grouped["data1"].nlargest(1)

key1
a     5    1.449857
b     4    0.965766
Name: data1, dtype: float64

In [ ]:
def peak_to_peak(arr):
    return arr.max() - arr.min()
grouped.aggregate(peak_to_peak)
# aggregate(函数) = “对每个组应用这个统计函数

      key2     data1     data2
key1
a        1  2.576385  3.566966
b        1  2.791021  0.328007

In [75]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0  0.309763  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0 -0.429744  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     1.027909  1.449857   3.0 -1.143076  1.844408 -3.197993 -1.899100
b     0.268011  0.965766   2.0  0.370920  0.231936  0.206916  0.288918


           50%       75%       max
key1
a    -0.600208 -0.115617  0.368974
b     0.370920  0.452922  0.534924

[2 rows x 24 columns]

In [77]:
tips = pd.read_csv("examples/tips.csv")
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [78]:
tips["tips_percent"] = tips["tip"] / tips["total_bill"]
tips

     total_bill   tip smoker   day    time  size  tips_percent
0         16.99  1.01     No   Sun  Dinner     2      0.059447
1         10.34  1.66     No   Sun  Dinner     3      0.160542
2         21.01  3.50     No   Sun  Dinner     3      0.166587
3         23.68  3.31     No   Sun  Dinner     2      0.139780
4         24.59  3.61     No   Sun  Dinner     4      0.146808
..          ...   ...    ...   ...     ...   ...           ...
239       29.03  5.92     No   Sat  Dinner     3      0.203927
240       27.18  2.00    Yes   Sat  Dinner     2      0.073584
241       22.67  2.00    Yes   Sat  Dinner     2      0.088222
242       17.82  1.75     No   Sat  Dinner     2      0.098204
243       18.78  3.00     No  Thur  Dinner     2      0.159744

[244 rows x 7 columns]

In [81]:
grouped = tips.groupby(['tip','smoker'])
grouped.describe()

             total_bill                                                       \
                  count   mean       std    min    25%    50%     75%    max
tip   smoker
1.00  No            1.0   7.25       NaN   7.25   7.25   7.25   7.250   7.25
      Yes           3.0   7.14  4.914702   3.07   4.41   5.75   9.175  12.60
1.01  No            1.0  16.99       NaN  16.99  16.99  16.99  16.990  16.99
1.10  Yes           1.0  12.90       NaN  12.90  12.90  12.90  12.900  12.90
1.17  Yes           1.0  32.83       NaN  32.83  32.83  32.83  32.830  32.83
...                 ...    ...       ...    ...    ...    ...     ...    ...
6.70  No            1.0  34.30       NaN  34.30  34.30  34.30  34.300  34.30
6.73  No            1.0  48.27       NaN  48.27  48.27  48.27  48.270  48.27
7.58  No            1.0  39.42       NaN  39.42  39.42  39.42  39.420  39.42
9.00  No            1.0  48.33       NaN  48.33  48.33  48.33  48.330  48.33
10.00 Yes           1.0  50.81       NaN  50.81  50.81  50.81  50.810  50.81

              size            ...           tips_percent                      \
             count      mean  ...  75%  max        count      mean       std
tip   smoker                  ...
1.00  No       1.0  1.000000  ...  1.0  1.0          1.0  0.137931       NaN
      Yes      3.0  1.666667  ...  2.0  2.0          3.0  0.193004  0.124288
1.01  No       1.0  2.000000  ...  2.0  2.0          1.0  0.059447       NaN
1.10  Yes      1.0  2.000000  ...  2.0  2.0          1.0  0.085271       NaN
1.17  Yes      1.0  2.000000  ...  2.0  2.0          1.0  0.035638       NaN
...            ...       ...  ...  ...  ...          ...       ...       ...
6.70  No       1.0  6.000000  ...  6.0  6.0          1.0  0.195335       NaN
6.73  No       1.0  4.000000  ...  4.0  4.0          1.0  0.139424       NaN
7.58  No       1.0  4.000000  ...  4.0  4.0          1.0  0.192288       NaN
9.00  No       1.0  4.000000  ...  4.0  4.0          1.0  0.186220       NaN
10.00 Yes      1.0  3.000000  ...  3.0  3.0          1.0  0.196812       NaN


                   min       25%       50%       75%       max
tip   smoker
1.00  No      0.137931  0.137931  0.137931  0.137931  0.137931
      Yes     0.079365  0.126639  0.173913  0.249823  0.325733
1.01  No      0.059447  0.059447  0.059447  0.059447  0.059447
1.10  Yes     0.085271  0.085271  0.085271  0.085271  0.085271
1.17  Yes     0.035638  0.035638  0.035638  0.035638  0.035638
...                ...       ...       ...       ...       ...
6.70  No      0.195335  0.195335  0.195335  0.195335  0.195335
6.73  No      0.139424  0.139424  0.139424  0.139424  0.139424
7.58  No      0.192288  0.192288  0.192288  0.192288  0.192288
9.00  No      0.186220  0.186220  0.186220  0.186220  0.186220
10.00 Yes     0.196812  0.196812  0.196812  0.196812  0.196812

[141 rows x 24 columns]

In [83]:
grouped_percent = grouped['tips_percent']

In [ ]:
grouped_percent.agg('mean')
# 使用名为mean的聚合规则

tip    smoker
1.00   No        0.137931
       Yes       0.193004
1.01   No        0.059447
1.10   Yes       0.085271
1.17   Yes       0.035638
                   ...
6.70   No        0.195335
6.73   No        0.139424
7.58   No        0.192288
9.00   No        0.186220
10.00  Yes       0.196812
Name: tips_percent, Length: 141, dtype: float64

In [ ]:
# 等价于（传函数对象）
grouped_percent.agg(np.mean)

tip    smoker
1.00   No        0.137931
       Yes       0.193004
1.01   No        0.059447
1.10   Yes       0.085271
1.17   Yes       0.035638
                   ...
6.70   No        0.195335
6.73   No        0.139424
7.58   No        0.192288
9.00   No        0.186220
10.00  Yes       0.196812
Name: tips_percent, Length: 141, dtype: float64

In [ ]:
grouped_percent.agg(["mean", "std", peak_to_peak]).head()
# 计算平均值，方差，极差

                 mean       std  peak_to_peak
tip  smoker
1.00 No      0.137931       NaN      0.000000
     Yes     0.193004  0.124288      0.246368
1.01 No      0.059447       NaN      0.000000
1.10 Yes     0.085271       NaN      0.000000
1.17 Yes     0.035638       NaN      0.000000

In [ ]:
grouped_percent.agg([('average','mean'),('stdev',np.std)])
# 自定义名称

               average     stdev
tip   smoker
1.00  No      0.137931  0.000000
      Yes     0.193004  0.101481
1.01  No      0.059447  0.000000
1.10  Yes     0.085271  0.000000
1.17  Yes     0.035638  0.000000
...                ...       ...
6.70  No      0.195335  0.000000
6.73  No      0.139424  0.000000
7.58  No      0.192288  0.000000
9.00  No      0.186220  0.000000
10.00 Yes     0.196812  0.000000

[141 rows x 2 columns]

In [94]:
functions = ['count','mean','max']
functions

['count', 'mean', 'max']

In [98]:
result = grouped[['tips_percent','total_bill']].agg(functions)
result
# 将调用的函数封装在functions

             tips_percent                     total_bill
                    count      mean       max      count   mean    max
tip   smoker
1.00  No                1  0.137931  0.137931          1   7.25   7.25
      Yes               3  0.193004  0.325733          3   7.14  12.60
1.01  No                1  0.059447  0.059447          1  16.99  16.99
1.10  Yes               1  0.085271  0.085271          1  12.90  12.90
1.17  Yes               1  0.035638  0.035638          1  32.83  32.83
...                   ...       ...       ...        ...    ...    ...
6.70  No                1  0.195335  0.195335          1  34.30  34.30
6.73  No                1  0.139424  0.139424          1  48.27  48.27
7.58  No                1  0.192288  0.192288          1  39.42  39.42
9.00  No                1  0.186220  0.186220          1  48.33  48.33
10.00 Yes               1  0.196812  0.196812          1  50.81  50.81

[141 rows x 6 columns]

In [100]:
grouped.agg({'tip':np.max,'size':"sum"})

                tip  size
tip   smoker
1.00  No       1.00     1
      Yes      1.00     5
1.01  No       1.01     2
1.10  Yes      1.10     2
1.17  Yes      1.17     2
...             ...   ...
6.70  No       6.70     6
6.73  No       6.73     4
7.58  No       7.58     4
9.00  No       9.00     4
10.00 Yes     10.00     3

[141 rows x 2 columns]

In [102]:
grouped.agg({"tips_percent":['min','max','mean','std'],'size':"sum"})

             tips_percent                               size
                      min       max      mean       std  sum
tip   smoker
1.00  No         0.137931  0.137931  0.137931       NaN    1
      Yes        0.079365  0.325733  0.193004  0.124288    5
1.01  No         0.059447  0.059447  0.059447       NaN    2
1.10  Yes        0.085271  0.085271  0.085271       NaN    2
1.17  Yes        0.035638  0.035638  0.035638       NaN    2
...                   ...       ...       ...       ...  ...
6.70  No         0.195335  0.195335  0.195335       NaN    6
6.73  No         0.139424  0.139424  0.139424       NaN    4
7.58  No         0.192288  0.192288  0.192288       NaN    4
9.00  No         0.186220  0.186220  0.186220       NaN    4
10.00 Yes        0.196812  0.196812  0.196812       NaN    3

[141 rows x 5 columns]

In [108]:
grouped =tips.groupby(['day','smoker'],as_index=False)
# 保留为列索引
grouped.mean(numeric_only=True)
# 字符串不参与平均

    day smoker  total_bill       tip      size  tips_percent
0   Fri     No   18.420000  2.812500  2.250000      0.151650
1   Fri    Yes   16.813333  2.714000  2.066667      0.174783
2   Sat     No   19.661778  3.102889  2.555556      0.158048
3   Sat    Yes   21.276667  2.875476  2.476190      0.147906
4   Sun     No   20.506667  3.167895  2.929825      0.160113
5   Sun    Yes   24.120000  3.516842  2.578947      0.187250
6  Thur     No   17.113111  2.673778  2.488889      0.160298
7  Thur    Yes   19.190588  3.030000  2.352941      0.163863

In [118]:
def top(df,n=5,columns='tips_percent'):
    return df.sort_values(columns,ascending=False)
display(df)
top(tips,n=6)

  key1  key2     data1     data2
0    a     1  0.605962 -3.197993
1    a     2 -1.126528 -0.600208
2  NaN     1  1.302704 -0.024254
3    b     2 -1.825254  0.534924
4    b     1  0.965766  0.206916
5    a  <NA>  1.449857  0.368974
6  NaN     1  1.354600 -1.323313

     total_bill   tip smoker  day    time  size  tips_percent
172        7.25  5.15    Yes  Sun  Dinner     2      0.710345
178        9.60  4.00    Yes  Sun  Dinner     2      0.416667
67         3.07  1.00    Yes  Sat  Dinner     1      0.325733
232       11.61  3.39     No  Sat  Dinner     2      0.291990
183       23.17  6.50    Yes  Sun  Dinner     4      0.280535
..          ...   ...    ...  ...     ...   ...           ...
187       30.46  2.00    Yes  Sun  Dinner     5      0.065660
0         16.99  1.01     No  Sun  Dinner     2      0.059447
57        26.41  1.50     No  Sat  Dinner     2      0.056797
102       44.30  2.50    Yes  Sat  Dinner     3      0.056433
237       32.83  1.17    Yes  Sat  Dinner     2      0.035638

[244 rows x 7 columns]

In [115]:
tips.groupby("smoker",as_index=True).apply(top)

            total_bill   tip   day    time  size  tips_percent
smoker
No     232       11.61  3.39   Sat  Dinner     2      0.291990
       149        7.51  2.00  Thur   Lunch     2      0.266312
       51        10.29  2.60   Sun  Dinner     2      0.252672
       185       20.69  5.00   Sun  Dinner     5      0.241663
       88        24.71  5.85  Thur   Lunch     2      0.236746
Yes    172        7.25  5.15   Sun  Dinner     2      0.710345
       178        9.60  4.00   Sun  Dinner     2      0.416667
       67         3.07  1.00   Sat  Dinner     1      0.325733
       183       23.17  6.50   Sun  Dinner     4      0.280535
       109       14.31  4.00   Sat  Dinner     2      0.279525

In [121]:
tips.groupby(['smoker','day']).apply(top,n=1,columns="total_bill")
# 每个分组只取totalbill最大的一条

                 total_bill   tip    time  size  tips_percent
smoker day
No     Fri  94        22.75  3.25  Dinner     2      0.142857
            91        22.49  3.50  Dinner     2      0.155625
            223       15.98  3.00   Lunch     3      0.187735
            99        12.46  1.50  Dinner     2      0.120385
       Sat  212       48.33  9.00  Dinner     4      0.186220
...                     ...   ...     ...   ...           ...
Yes    Thur 199       13.51  2.00   Lunch     2      0.148038
            198       13.00  2.00   Lunch     2      0.153846
            202       13.00  2.00   Lunch     2      0.153846
            201       12.74  2.01   Lunch     2      0.157771
            196       10.34  2.00   Lunch     2      0.193424

[244 rows x 5 columns]

In [123]:
frame = pd.DataFrame({"data1": np.random.standard_normal(1000),
                       "data2": np.random.standard_normal(1000)})
frame

        data1     data2
0   -1.837355  0.281881
1    0.372923 -1.175003
2   -0.706918  0.066886
3   -0.257835 -1.676320
4    0.903911  0.894459
..        ...       ...
995  0.223446  1.709632
996 -0.919099  0.644666
997 -0.426846 -0.459815
998 -0.660393  0.455892
999  1.163858  0.605287

[1000 rows x 2 columns]

In [ ]:
quartilies = pd.cut(frame["data1"],4)
quartilies

0      (-1.88, 0.098]
1      (0.098, 2.076]
2      (-1.88, 0.098]
3      (-1.88, 0.098]
4      (0.098, 2.076]
            ...
995    (0.098, 2.076]
996    (-1.88, 0.098]
997    (-1.88, 0.098]
998    (-1.88, 0.098]
999    (0.098, 2.076]
Name: data1, Length: 1000, dtype: category
Categories (4, interval[float64, right]): [(-3.865, -1.88] < (-1.88, 0.098] < (0.098, 2.076] < (2.076, 4.053]]

In [133]:
def get_stats(group):
    return pd.DataFrame(
        {'min':group.min,'max':group.max,
        'count':group.count(),
        'mean':group.mean()}
    )
grouped = frame.groupby(quartilies)
grouped.apply(get_stats)

                                                                     min  \
data1
(-3.865, -1.88] data1  <bound method DataFrame.min of         data1  ...
                data2  <bound method DataFrame.min of         data1  ...
(-1.88, 0.098]  data1  <bound method DataFrame.min of         data1  ...
                data2  <bound method DataFrame.min of         data1  ...
(0.098, 2.076]  data1  <bound method DataFrame.min of         data1  ...
                data2  <bound method DataFrame.min of         data1  ...
(2.076, 4.053]  data1  <bound method DataFrame.min of         data1  ...
                data2  <bound method DataFrame.min of         data1  ...

                                                                     max  \
data1
(-3.865, -1.88] data1  <bound method DataFrame.max of         data1  ...
                data2  <bound method DataFrame.max of         data1  ...
(-1.88, 0.098]  data1  <bound method DataFrame.max of         data1  ...
                data2  <bound method DataFrame.max of         data1  ...
(0.098, 2.076]  data1  <bound method DataFrame.max of         data1  ...
                data2  <bound method DataFrame.max of         data1  ...
(2.076, 4.053]  data1  <bound method DataFrame.max of         data1  ...
                data2  <bound method DataFrame.max of         data1  ...

                       count      mean
data1
(-3.865, -1.88] data1     32 -2.306400
                data2     32 -0.178775
(-1.88, 0.098]  data1    510 -0.630668
                data2    510  0.024906
(0.098, 2.076]  data1    436  0.792570
                data2    436  0.066075
(2.076, 4.053]  data1     22  2.455097
                data2     22 -0.124801

In [128]:
# 等价于
grouped.agg(['min','max','count','mean'])

                    data1                               data2                  \
                      min       max count      mean       min       max count
data1
(-3.865, -1.88] -3.857462 -1.891199    32 -2.306400 -1.473172  1.409328    32
(-1.88, 0.098]  -1.870985  0.097576   510 -0.630668 -2.584584  4.121760   510
(0.098, 2.076]   0.099014  2.017419   436  0.792570 -2.525056  3.133602   436
(2.076, 4.053]   2.092352  4.053484    22  2.455097 -1.641659  1.610268    22


                     mean
data1
(-3.865, -1.88] -0.178775
(-1.88, 0.098]   0.024906
(0.098, 2.076]   0.066075
(2.076, 4.053]  -0.124801

In [ ]:
quartiles_samp = pd.qcut(frame["data1"], 4, labels=False)
# 不返回区间标签，返回编号
quartiles_samp.head()

0    0
1    2
2    0
3    1
4    3
Name: data1, dtype: int64

In [139]:
grouped = frame.groupby(quartiles_samp)
grouped.apply(get_stats)

                                                           min  \
data1
0     data1  <bound method DataFrame.min of         data1  ...
      data2  <bound method DataFrame.min of         data1  ...
1     data1  <bound method DataFrame.min of         data1  ...
      data2  <bound method DataFrame.min of         data1  ...
2     data1  <bound method DataFrame.min of         data1  ...
      data2  <bound method DataFrame.min of         data1  ...
3     data1  <bound method DataFrame.min of         data1  ...
      data2  <bound method DataFrame.min of         data1  ...

                                                           max  count  \
data1
0     data1  <bound method DataFrame.max of         data1  ...    250
      data2  <bound method DataFrame.max of         data1  ...    250
1     data1  <bound method DataFrame.max of         data1  ...    250
      data2  <bound method DataFrame.max of         data1  ...    250
2     data1  <bound method DataFrame.max of         data1  ...    250
      data2  <bound method DataFrame.max of         data1  ...    250
3     data1  <bound method DataFrame.max of         data1  ...    250
      data2  <bound method DataFrame.max of         data1  ...    250

                 mean
data1
0     data1 -1.260007
      data2  0.085564
1     data1 -0.328580
      data2 -0.065006
2     data1  0.301913
      data2  0.049255
3     data1  1.303181
      data2  0.062365

In [140]:
states = ["Ohio", "New York", "Vermont", "Florida",
           "Oregon", "Nevada", "California", "Idaho"]

group_key = ["East", "East", "East", "East",
              "West", "West", "West", "West"]

data = pd.Series(np.random.standard_normal(8), index=states)

data

Ohio          1.092428
New York     -0.269155
Vermont       2.396308
Florida      -1.061406
Oregon        1.544582
Nevada        0.935291
California    0.015557
Idaho        -1.909383
dtype: float64

In [141]:
data[["Vermont", "Nevada", "Idaho"]] = np.nan

In [142]:
data

Ohio          1.092428
New York     -0.269155
Vermont            NaN
Florida      -1.061406
Oregon        1.544582
Nevada             NaN
California    0.015557
Idaho              NaN
dtype: float64

In [143]:
data.groupby(group_key).size()

East    4
West    4
dtype: int64

In [144]:
data.groupby(group_key).count()

East    3
West    2
dtype: int64

In [ ]:
def fill_mean(group):
    return group.fillna(group.mean())
data.groupby(group_key).apply(fill_mean)
# 按照均值补充缺失值

East  Ohio          1.092428
      New York     -0.269155
      Vermont      -0.079378
      Florida      -1.061406
West  Oregon        1.544582
      Nevada        0.780069
      California    0.015557
      Idaho         0.780069
dtype: float64

In [ ]:
fill_values = {"East":0.5,"West":1}
def fill_func(group):
    return group.fillna(fill_values[group.name])
data.groupby(group_key).apply(fill_func)
# 按照组内部name，设置每组缺失值的预设值然后填充

East  Ohio          1.092428
      New York     -0.269155
      Vermont       0.500000
      Florida      -1.061406
West  Oregon        1.544582
      Nevada        1.000000
      California    0.015557
      Idaho         1.000000
dtype: float64

In [149]:
suits = ["H", "S", "C", "D"]  # Hearts, Spades, Clubs, Diamonds
card_val = (list(range(1, 11)) + [10] * 3) * 4
base_names = ["A"] + list(range(2, 11)) + ["J", "K", "Q"]
cards = []
for suit in suits:
    cards.extend(str(num) + suit for num in base_names)

deck = pd.Series(card_val, index=cards)

In [150]:
deck

AH      1
2H      2
3H      3
4H      4
5H      5
6H      6
7H      7
8H      8
9H      9
10H    10
JH     10
KH     10
QH     10
AS      1
2S      2
3S      3
4S      4
5S      5
6S      6
7S      7
8S      8
9S      9
10S    10
JS     10
KS     10
QS     10
AC      1
2C      2
3C      3
4C      4
5C      5
6C      6
7C      7
8C      8
9C      9
10C    10
JC     10
KC     10
QC     10
AD      1
2D      2
3D      3
4D      4
5D      5
6D      6
7D      7
8D      8
9D      9
10D    10
JD     10
KD     10
QD     10
dtype: int64

In [151]:
# 加权平均
df = pd.DataFrame({"category": ["a", "a", "a", "a",
                                 "b", "b", "b", "b"],
                    "data": np.random.standard_normal(8),
                    "weights": np.random.uniform(size=8)})
df

  category      data   weights
0        a -0.932185  0.044360
1        a -1.694670  0.382295
2        a -0.453002  0.416512
3        a  1.006153  0.983236
4        b -0.787305  0.428976
5        b -1.510875  0.344431
6        b -1.642907  0.749003
7        b  0.103872  0.772216

In [153]:
grouped = df.groupby("category")
def get_wavg(group):
    return np.average(group['data'],weights=group['weights'])
grouped.apply(get_wavg)

category
a    0.060988
b   -0.875288
dtype: float64

In [154]:
close_px = pd.read_csv("examples/stock_px.csv",parse_dates=True,
                       index_col=0)
# 将日期列设置为时间类型，第一列设置为索引

In [155]:
close_px.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2214 entries, 2003-01-02 to 2011-10-14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2214 non-null   float64
 1   MSFT    2214 non-null   float64
 2   XOM     2214 non-null   float64
 3   SPX     2214 non-null   float64
dtypes: float64(4)
memory usage: 86.5 KB

In [162]:
close_px.head()

            AAPL   MSFT    XOM     SPX
2003-01-02  7.40  21.11  29.22  909.03
2003-01-03  7.45  21.14  29.24  908.59
2003-01-06  7.45  21.52  29.96  929.01
2003-01-07  7.43  21.93  28.95  922.93
2003-01-08  7.28  21.31  28.83  909.93

In [156]:
def spx_corr(group):
    return group.corrwith(group['SPX'])
# 对 group 这个分组数据里的每一列，都去和 group['SPX'] 做相关系数计算。

In [158]:
reteruns = close_px.pct_change().dropna()

In [159]:
def get_year(x):
    return x.year

In [160]:
by_year = reteruns.groupby(get_year)

In [161]:
by_year.apply(spx_corr)

          AAPL      MSFT       XOM  SPX
2003  0.541124  0.745174  0.661265  1.0
2004  0.374283  0.588531  0.557742  1.0
2005  0.467540  0.562374  0.631010  1.0
2006  0.428267  0.406126  0.518514  1.0
2007  0.508118  0.658770  0.786264  1.0
2008  0.681434  0.804626  0.828303  1.0
2009  0.707103  0.654902  0.797921  1.0
2010  0.710105  0.730118  0.839057  1.0
2011  0.691931  0.800996  0.859975  1.0

把股票价格数据读进来，先算每日收益率，再按年份分组，最后求每年里各股票和 SPX 的相关系数
def spx_corr(group):
    return group.corrwith(group['SPX'])
输入一个分组后的子表group，让group中的每列与spx做相关系数计算
pct_change()：计算相邻两天的百分比变化
通过dropna丢弃第一行的空值
def get_year(x):
    return x.year
x为索引里的每个日期，get_year()是专门用于取年份的函数
by_year = reteruns.groupby(get_year)
按照年份分组
by_year.apply(spx_corr)
对每一年都应用spx_corr函数

In [163]:
import statsmodels.api as sm

In [164]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
                    'value': np.arange(12.)})
df

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [185]:
g = df.groupby('key')['value']

In [168]:
g.mean()

     value
key
a      4.5
b      5.5
c      6.5

In [ ]:
def get_mean(group):
    return group.mean()

g.transform(get_mean)
# 对 g 的每个分组求均值，然后把结果“按原来的行形状展开返回”
# transform 会把“每组算出来的结果”再对齐回原来的每一行。

    value
0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5

In [184]:
g.transform('mean')

    value
0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5

In [172]:
def times_two(group):
    return group * 2

g.transform(times_two)

    value
0     0.0
1     2.0
2     4.0
3     6.0
4     8.0
5    10.0
6    12.0
7    14.0
8    16.0
9    18.0
10   20.0
11   22.0

In [173]:
def get_rank(group):
    return group.rank(ascending=False)

g.transform(get_rank)
# 按数据大小排序

    value
0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0

In [175]:
def normalize(x):
    return (x-x.mean()) / x.std()
# 把不同量纲、不同大小范围的数据拉到可比较的尺度上
g.transform(normalize)
# 对每个分组分别做标准化,每个组内部都减去本组均值、再除以本组标准差

       value
0  -1.161895
1  -1.161895
2  -1.161895
3  -0.387298
4  -0.387298
5  -0.387298
6   0.387298
7   0.387298
8   0.387298
9   1.161895
10  1.161895
11  1.161895

In [176]:
g.apply(normalize)

           value
key
a   0  -1.161895
    3  -0.387298
    6   0.387298
    9   1.161895
b   1  -1.161895
    4  -0.387298
    7   0.387298
    10  1.161895
c   2  -1.161895
    5  -0.387298
    8   0.387298
    11  1.161895

In [177]:
g.transform('mean')

    value
0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5

In [182]:
df

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [ ]:
normalized = (df['value'] - g.transform('mean')) / g.transform("std")

normalized
# 不进行包装也可进行分组操作
# 保持索引一致，均为value列的series

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

transform输入一个组，输出一个和组长度一致的结果拼回原数据的行结构
agg.将每组压缩成汇总值

In [187]:
tips

     total_bill   tip smoker   day    time  size  tips_percent
0         16.99  1.01     No   Sun  Dinner     2      0.059447
1         10.34  1.66     No   Sun  Dinner     3      0.160542
2         21.01  3.50     No   Sun  Dinner     3      0.166587
3         23.68  3.31     No   Sun  Dinner     2      0.139780
4         24.59  3.61     No   Sun  Dinner     4      0.146808
..          ...   ...    ...   ...     ...   ...           ...
239       29.03  5.92     No   Sat  Dinner     3      0.203927
240       27.18  2.00    Yes   Sat  Dinner     2      0.073584
241       22.67  2.00    Yes   Sat  Dinner     2      0.088222
242       17.82  1.75     No   Sat  Dinner     2      0.098204
243       18.78  3.00     No  Thur  Dinner     2      0.159744

[244 rows x 7 columns]

In [190]:
tips.pivot_table(index=['day','smoker'],
                 values=['size','tip','tips_percent','total_bill'])
# 默认为平均值，按 day 和 smoker 分组，计算 size、tip、tips_percent、total_bill 这些列的平均值。

                 size       tip  tips_percent  total_bill
day  smoker
Fri  No      2.250000  2.812500      0.151650   18.420000
     Yes     2.066667  2.714000      0.174783   16.813333
Sat  No      2.555556  3.102889      0.158048   19.661778
     Yes     2.476190  2.875476      0.147906   21.276667
Sun  No      2.929825  3.167895      0.160113   20.506667
     Yes     2.578947  3.516842      0.187250   24.120000
Thur No      2.488889  2.673778      0.160298   17.113111
     Yes     2.352941  3.030000      0.163863   19.190588

In [191]:
tips.pivot_table(index=['time','day'],columns="smoker",
                 values=['tips_percent','size'])

                 size           tips_percent
smoker             No       Yes           No       Yes
time   day
Dinner Fri   2.000000  2.222222     0.139622  0.165347
       Sat   2.555556  2.476190     0.158048  0.147906
       Sun   2.929825  2.578947     0.160113  0.187250
       Thur  2.000000       NaN     0.159744       NaN
Lunch  Fri   3.000000  1.833333     0.187735  0.188937
       Thur  2.500000  2.352941     0.160311  0.163863

In [196]:
tips.groupby(['time','day','smoker'],as_index=False)[['tips_percent','size']].mean()

      time   day smoker  tips_percent      size
0   Dinner   Fri     No      0.139622  2.000000
1   Dinner   Fri    Yes      0.165347  2.222222
2   Dinner   Sat     No      0.158048  2.555556
3   Dinner   Sat    Yes      0.147906  2.476190
4   Dinner   Sun     No      0.160113  2.929825
5   Dinner   Sun    Yes      0.187250  2.578947
6   Dinner  Thur     No      0.159744  2.000000
7    Lunch   Fri     No      0.187735  3.000000
8    Lunch   Fri    Yes      0.188937  1.833333
9    Lunch  Thur     No      0.160311  2.500000
10   Lunch  Thur    Yes      0.163863  2.352941

In [203]:
meantip = tips.pivot_table(index=['time','day'],columns='smoker',
                 values=['tips_percent','size'],margins=True)
meantip
# margins表示最后一行，列总计（平均值）

                 size                     tips_percent
smoker             No       Yes       All           No       Yes       All
time   day
Dinner Fri   2.000000  2.222222  2.166667     0.139622  0.165347  0.158916
       Sat   2.555556  2.476190  2.517241     0.158048  0.147906  0.153152
       Sun   2.929825  2.578947  2.842105     0.160113  0.187250  0.166897
       Thur  2.000000       NaN  2.000000     0.159744       NaN  0.159744
Lunch  Fri   3.000000  1.833333  2.000000     0.187735  0.188937  0.188765
       Thur  2.500000  2.352941  2.459016     0.160311  0.163863  0.161301
All          2.668874  2.408602  2.569672     0.159328  0.163196  0.160803

In [205]:
meantip = meantip.fillna(meantip.mean())
meantip

                 size                     tips_percent
smoker             No       Yes       All           No       Yes       All
time   day
Dinner Fri   2.000000  2.222222  2.166667     0.139622  0.165347  0.158916
       Sat   2.555556  2.476190  2.517241     0.158048  0.147906  0.153152
       Sun   2.929825  2.578947  2.842105     0.160113  0.187250  0.166897
       Thur  2.000000  2.312039  2.000000     0.159744  0.169417  0.159744
Lunch  Fri   3.000000  1.833333  2.000000     0.187735  0.188937  0.188765
       Thur  2.500000  2.352941  2.459016     0.160311  0.163863  0.161301
All          2.668874  2.408602  2.569672     0.159328  0.163196  0.160803

In [201]:
tips.pivot_table(index=["time", "size", "smoker"], columns="day",
                  values="tips_percent", fill_value=0)

day                      Fri       Sat       Sun      Thur
time   size smoker
Dinner 1    No      0.000000  0.137931  0.000000  0.000000
            Yes     0.000000  0.325733  0.000000  0.000000
       2    No      0.139622  0.162705  0.168859  0.159744
            Yes     0.171297  0.148668  0.207893  0.000000
       3    No      0.000000  0.154661  0.152663  0.000000
            Yes     0.000000  0.144995  0.152660  0.000000
       4    No      0.000000  0.150096  0.148143  0.000000
            Yes     0.117750  0.124515  0.193370  0.000000
       5    No      0.000000  0.000000  0.206928  0.000000
            Yes     0.000000  0.106572  0.065660  0.000000
       6    No      0.000000  0.000000  0.103799  0.000000
Lunch  1    No      0.000000  0.000000  0.000000  0.181728
            Yes     0.223776  0.000000  0.000000  0.000000
       2    No      0.000000  0.000000  0.000000  0.166005
            Yes     0.181969  0.000000  0.000000  0.158843
       3    No      0.187735  0.000000  0.000000  0.084246
            Yes     0.000000  0.000000  0.000000  0.204952
       4    No      0.000000  0.000000  0.000000  0.138919
            Yes     0.000000  0.000000  0.000000  0.155410
       5    No      0.000000  0.000000  0.000000  0.121389
       6    No      0.000000  0.000000  0.000000  0.173706

In [206]:
from io import StringIO

In [208]:
data = """Sample  Nationality  Handedness
   .....: 1   USA  Right-handed
   .....: 2   Japan    Left-handed
   .....: 3   USA  Right-handed
   .....: 4   Japan    Right-handed
   .....: 5   Japan    Left-handed
   .....: 6   Japan    Right-handed
   .....: 7   USA  Right-handed
   .....: 8   USA  Left-handed
   .....: 9   Japan    Right-handed
   .....: 10  USA  Right-handed"""
data

'Sample  Nationality  Handedness\n1   USA  Right-handed\n2   Japan    Left-handed\n3   USA  Right-handed\n4   Japan    Right-handed\n5   Japan    Left-handed\n6   Japan    Right-handed\n7   USA  Right-handed\n8   USA  Left-handed\n9   Japan    Right-handed\n10  USA  Right-handed'

In [ ]:
data = pd.read_table(StringIO(data),sep="\s+")
# 使用stringIO将长字符串伪装成文件供pd.read_table()读取；相当于一个临时文本文件

TypeError: initial_value must be str or None, not DataFrame

In [212]:
data

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

In [ ]:
pd.crosstab(data['Nationality'],data["Handedness"],margins=True)
# 做交叉表统计，设置行，列，统计单元格出现次数

Handedness   Left-handed  Right-handed  All
Nationality
Japan                  2             3    5
USA                    1             4    5
All                    3             7   10

In [215]:
pd.crosstab([tips['time'],tips['day']],tips['smoker'],margins=True)
# crosstab前两个参数可以是数组也可以是序列或数组的序列

smoker        No  Yes  All
time   day
Dinner Fri     3    9   12
       Sat    45   42   87
       Sun    57   19   76
       Thur    1    0    1
Lunch  Fri     1    6    7
       Thur   44   17   61
All          151   93  244